### ISSUE TITLE
Generalize description of SR-TE tunnel

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#88]
Based on IETF 113 discussion: https://notes.ietf.org/notes-ietf-113-teas

Based on IETF 114 discussion: https://notes.ietf.org/notes-ietf-114-teas

**Tasks:**

- [x] https://github.com/FabioPeruzzini/actn-poi/issues/88#issuecomment-1245316313

**Comment by italobusi** [comment]
**[2022-03-29 ACTN POI Call (Slot 1)](https://demo.hedgedoc.org/sRDV7vcNSSeSS11g5-TuAw)**

Suggestion from Pavan:

> Pavan Beeram: The ideal scenario would be to describe the procedures in a path-control-technology (RSVP/SR) agnostic way and then add technology specific examples wherever there is a deviation.

It is not clear how RSVP-TE can be used end-to-end. One possibility is to do LSP stitching

Jeff: RSVP-TE end-to-end is not widely used in the network. Usually BGP-LU is used with RSVP-TE

Daniele: there are two BGP extensions for multi-domain services which are better fitting when there is a need to map a service with an LSP: BGP-CT (classfull transport) and BGP-CAR (color-aware routing)

References:
- https://datatracker.ietf.org/doc/draft-dskc-bess-bgp-car-problem-statement/
- https://datatracker.ietf.org/doc/draft-kaliraj-idr-bgp-classful-transport-planes/
- https://datatracker.ietf.org/doc/draft-dskc-bess-bgp-car/

We can update the text to generalize RSVP-TE and SR-TE end-to-end descriptions even though the procedures will be most likely used for SR-TE end-to-end

To be discussed also with Brent next week and, if needed, we can trigger some more discussion on the TEAS WG mailing list regarding the proposal to generalize the description of RSVP-TE and SR-TE end-to-end, leaving the BGP-LU outside the scope of the document

**Comment by italobusi** [comment]
**[2022-05-03 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-05-03.md)**

Slides describing two examples of a common procedure based on TE tunnel model reviewed and discussed: 
[multi-domain-path-options-00.pptx](https://github.com/FabioPeruzzini/actn-poi/files/8642311/multi-domain-path-options-00.pptx)

The SR-TE option is in line with the description in the current draft

Some implementation issues have been identified with the option based on LSP stitching between two RSVP-TE domains:
- the slide is assuming that the BR would be able to stitch between a static LSP segment and a dynamic LSP segment, but ths feature is not (widely) available on IP routers;
- an alternative approach could be to setup an RSVP-TE session (with an IGP instance) between the adjacent BRs, but this approach is not practical in real network deployments.

I has been agreed that the procedure described in the current draft cannot be generalized to cover the case where BGP-LYU is used, which is the most common solution in today's networks

Further investigation is needed to conclude that the SR-TE procedure described in the draft can be generalized to other solutions (e.g., LSP stitching between two RSVP-TE domains)

- [ ] @anton1688 / @jbrentfoster : provide further feedbacks about the applicability of the generalized procedure to other solutions (e.g., LSP stitching between two RSVP-TE domains)

Draft mail for TEAS WG under preparation in: https://demo.hedgedoc.org/jDNp8VE9QC6r3wuLLjPDmA

The text requires further updates based on the investigation of the feasibility to generalize the common description of the SR-TE procedure

- [ ] All: review the proposed text of the draft mail for TEAS WG

**Comment by italobusi** [comment]
Thinking further about the reply to TEAS WG, I am wondering whether we simplify our life and accept the proposal to generalize the description to cover any technology to which the TE tunnel applies at the MPI even if, for inter-domain TE (e.g., PE13-PE23), we have not identified any other feasible solution than SR-TE

In fact the description for the intra-domain case (e.g., PE13-PE14) applies to both SR-TE and RSVP-TE cases

**Comment by italobusi** [comment]
**[2022-05-17 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-05-17.md)**

> * [x]  @anton1688 / @jbrentfoster : provide further feedbacks about the applicability of the generalized procedure to other solutions (e.g., LSP stitching between two RSVP-TE domains)

Draft mail for TEAS WG under preparation in: https://demo.hedgedoc.org/jDNp8VE9QC6r3wuLLjPDmA

> - [ ] All: review the proposed text of the draft mail for TEAS WG

There was some support during the call for the text in option 3

Brent: we need to check that the text is generic enough to apply to both SR-MPLS and SRv6

- [ ] @jbrentfoster : check that the current text description is applicable also to SRv6

**Comment by italobusi** [comment]
**[2022-05-24 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-05-24.md)**

Draft mail for TEAS WG under preparation in: https://demo.hedgedoc.org/jDNp8VE9QC6r3wuLLjPDmA

Confirm agreement to propose option 3: the notes have been updated accordingly

> - [ ] All: review the proposed text of the draft mail for TEAS WG before Thursday May 26 EOB

- [ ] @italobusi : send the mail to TEAS WG (after review)

- [ ] @italobusi : Update the draft text based on the comment resolution

**Comment by italobusi** [comment]
**[2022-06-28 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-06-28.md)**

> [ ] @italobusi : Update the draft text based on the comment resolution

Draft PR #94 prepared (txt file to be generated) and reviewed during the call

- [ ] @italobusi : update the text as discussed and add the text file and open the PR
- [ ] @jbrentfoster / @Paolo-Volpato / @sergiobelotti : review the PR by the end of this week
- [ ] @jbouqui153 / @Paolo-Volpato : check whether the text in PR#94 can also close issue #91

**Comment by italobusi** [comment]
> * [x]  @italobusi : update the text as discussed and add the text file and open the PR
> *

https://github.com/FabioPeruzzini/actn-poi/pull/94/commits/4be2e2b050f89ee306e4d82a7dd71609723ef83c

**Comment by italobusi** [comment]
Re-opened based on feedbacks during IETF 114 discussion

**Comment by italobusi** [comment]
I have sent a mail to the chairs to better understand their feedbacks and done some detailed analysis where I have spotted few paragraphs that need further update:

section 2

OLD

```
   The MPI interface presents an abstracted topology to MDSC hiding
   technology-specific aspects of the network and hiding topology
   details depending on the policy chosen regarding the level of
   abstraction supported. The level of abstraction can be obtained based
   on P-PNC and O-PNC configuration parameters (e.g., provide the
   potential connectivity between any PE and any BR in an SR-TE
   network).
```
**NEW (TBD)**

---

section 2

OLD

```
   This document analyses the case where the packet networks support
   multi-domain SR-TE paths and the optical networks could be either a
   DWDM network or an OTN network (without DWDM layer) or multi-layer
   OTN/DWDM network. DWDM networks could be either fixed-grid or
   flexible-grid.
```

**NEW (TBD)**

---

Figure 2 needs to be updated: SR-TE path will be renamed as TE path: see #82 

---

section 4.3 (typo)

OLD

```
   The L3 Topology Model, TE Topology Model, TE Packet Topology Model
   and MPLS-TE Topology Model are used together to report the SR-TE
   network topology, as described in [MPLS-TE-TOPO].
```

NEW

```
   The L3 Topology Model, TE Topology Model, TE Packet Topology Model
   and MPLS-TE Topology Model are used together to report the MPLS-TE
   network topology, as described in [MPLS-TE-TOPO].
```

---

section 4.6

OLD

```
   A multi-layer intra-domain IP link and its supporting multi-layer
   intra-domain Ethernet link are discovered by the P-PNC like any other
   intra-domain IP and Ethernet links, as described in section 4.3, and
   reported at the MPI within the SR-TE and Ethernet network topologies,
   e.g., as shown in Figure 6.
```

**NEW (TBD)**

---

section 5

OLD

```
   o  PE13-P16-PE14 SR-TE path already exists but have not enough
      bandwidth to support the new L3VPN, as described in section 4.4;,
      and that:
```

**NEW (TBD)**

**Comment by italobusi** [comment]
**[2022-09-13 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-09-13.md)**

Jeff: in the gap analysis we are highlighting some missing attributes for SR-TE. Being just technology-agnostic would not help providing a complete gap analysis.

- [ ] @italobusi  : invite the TEAS WG chairs to join the slot 2 call on October 4th to address their comments

**Comment by italobusi** [comment]
> [x] @italobusi : invite the TEAS WG chairs to join the slot 2 call on October 4th to address their comments

**[2022-10-07 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-10-07.md)**

Not available this week: will invite them for the week on October 18th. If there is not enough time to finish the draft before IET 115, we can report the status of the discussion at IETF 115 and update the draft before IETF 116

- [ ] @italobusi  invite the TEAS WG chairs to join the slot 2 call on October 18th to address their comments

**Comment by italobusi** [comment]
> [x] @italobusi invite the TEAS WG chairs to join the slot 2 call on October 18th to address their comments

**[2022-10-18 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-10-18.md)**

Postponed to offline discussion with the chairs during IETF 115

The breakout meeting room Mezzanine 12 has been booked for the offline meeting on Monday November 7th at 3:00-3:30pm BST (break time)

- [ ] @italobusi invite the chairs to the offline meeting
- [ ] @ggalimba56 to send Webex meeting details

**Comment by ggalimba56** [comment]
Sent the invitation with Webex.

**Comment by italobusi** [comment]
**[2022-11-14 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-11-15.md)**

Discussed offline with Pavan and Daniel during IETF 115

Proposed resolution provided by Daniel together with additional review comments in PR #105 

The target plan is to complete the review of this PR during the next weekly call and to use the updated text as the basis for the next editorial round

Brent and Jeff has volunteered to review the PR. Additional reviews from other people are also encouraged.

**Comment by italobusi** [comment]
> * [x]  @danielkinguk check offline with Pavan if the updated document addresses his concerns

Pavan reported offline he is ok with the updated text so the issue has been closed
